### ISSUE TITLE
Can't use `BUILDKITE_PULL_REQUEST_BASE_BRANCH` in pipeline yml file

### ISSUE THREAD

**Issue by zhaoyi0113** [buildkite/agent#1096]
I create a build step which is only run when a PULL REQUEST is created on master branch. Below is my settings:

```
steps:
  - label: ":python: Test"
     command: make test
     skip: ${BUILDKITE_PULL_REQUEST_BASE_BRANCH} != "master"
```

But regardless what happens , this step is always executing even for branches other master. Did I make anything wrong? I see this environment variable is listed in https://buildkite.com/docs/pipelines/environment-variables
