### ISSUE TITLE
Pipeline upload command failed to set float number environment variable 

### ISSUE THREAD

**Issue by cuichenli** [buildkite/agent#1129]
The pipeline upload command is failing to set float number environment variables. I was trying to upload a pipeline with the following parts:
```
steps:
	- command: echo 1
      env: 
        STRING_VALUE: I can do it
        FLOAT_VALUE: 1.9
```
The intended outcome would be there are both environment variables `STRING_VALUE` and `FLOAT_VALUE` in the build, even though the `FLOAT_VALUE` would be converted to a string. While the actual case is I can only find `STRING_VALUE` in the build. To make it works, I need to add double quotes around the `1.9` and it will work fine. 

Is that possible the agent can convert float number to string automatically? Thanks!
