### ISSUE TITLE
Plugin command hook not executed when plugin is not the first

### ISSUE THREAD

**Issue by ahilsend** [buildkite/agent#1152]
The following pipeline will only execute the artifact download plugin, but not the docker command in agent version 3.18:

```yaml
  - label: my-step
    command: my-command.sh
    plugins:
    - artifacts#v1.2.0:
        download:
        ...
    - docker#v3.5.0:
        ...
```

Will result in no command being executed at all with this warning: 
`⚠️ Warning: Ignoring additional command hook (docker plugin, position 2)`

The cultprint appears to be https://github.com/buildkite/agent/pull/1135. It checks only the first plugin in the list, and then sets hookTypeSeen = true even though it didn't actually run anything.

**Comment by migueleliasweb** [comment]
I'm having the same problem.

The v3.18.0 version of the agents breaks compatibility with many current pipelines I manage.

Eg.

```yaml
steps:
  - name: ':terraform: :clipboard: Plan'
    plugins:
      cultureamp/aws-assume-role#v0.1.0:
        role: arn:aws:iam::${ACCOUNT_ID}:role/${ROLE}
      docker-compose#v3.0.2:
        pull: plan
        run: plan
      artifacts#v1.1.0:
        upload: tfplan
```

This pipeline itself does not fail but the step right after it triers to download the artifact and it fails as it wasn't uploaded in the step before - the artifact hooks weren't triggered.

| Plugin | Hooks | 
| -----|-----|
| [cultureamp/aws-assume-role#v0.1.0](https://github.com/cultureamp/aws-assume-role-buildkite-plugin/tree/v0.1.0/hooks) | pre-command | 
| [docker-compose#v3.0.2](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/tree/v3.0.2/hooks) | command, pre-checkout, pre-exit |
| [artifacts#v1.1.0](https://github.com/buildkite-plugins/artifacts-buildkite-plugin/tree/v1.1.0/hooks) |  post-command, pre-command |

![Screen Shot 2020-01-28 at 3 31 55 pm](https://user-images.githubusercontent.com/1608212/73235641-5c4aa980-41e3-11ea-8513-cc80606b3fb0.png)

Is there a plan on how to keep this feature working in this case? Are there any workarounds?

@ahilsend , in fact the issue is created in: https://github.com/buildkite/agent/pull/1135/files#diff-1d1158568615ba7f7c717c11183449f8R675
