### ISSUE TITLE
Use metadata in conditionals

### ISSUE THREAD

**Issue by evandam** [buildkite/agent#1155]
Hi there,

I'm looking to add a step in my pipeline to block and ask if tests should be run. Here's the general pattern:

```yaml
steps:
  - block: "Prompt for tests"
    fields:
      - select: "Run tests?"
        key: "run-tests"
        options:
          - label: "Sure"
            value: "yes"
          - label: "No thanks"
            value: "no"
    if: build.source == "ui"

  # Ideal approach using an "if" (feature request?)
  - label: "Run tests"
    key: test
    command: echo "test me!"
    if: build.metadata("run-tests", "false") == "true"
    plugins:
      - docker-compose#v3.1.0:
          run: app

  # Workaround, but doesn't work inside docker image without buildkite-agent
  - label: "Run tests take 2"
    key: test
    command: >
      if [ "$(buildkite-agent meta-data get run-tests --default false)" = "true" ]; then
        echo "test me!"
      else
        echo "tests skipped"
      fi
    plugins:
      - docker-compose#v3.1.0:
          run: app
```

I suppose another approach could be to have a hook that tries to read the metadata and export that as an environment variable that can be used, but it feels like a lot of work to do something that should be a native solution.

Any thoughts on this?

**Comment by sj26** [comment]
Hi @evandam! :wave:

Could you use a simple block step instead?

```yaml
steps:
  - block: "Run tests?"

  # Ideal approach using an "if" (feature request?)
  - label: "Run tests"
    command: echo "test me!"
    plugins:
      - docker-compose#v3.1.0:
          run: app
```

If this has to fit into a wider more complicated pipeline then you can use explicit dependencies:


```yaml
steps:
  - block: "Run tests"
    key: "run-tests"

  # Ideal approach using an "if" (feature request?)
  - label: "Run tests"
    key: tests
    depends_on: "run-tests"
    command: echo "test me!"
    plugins:
      - docker-compose#v3.1.0:
          run: app
```

**Comment by evandam** [comment]
Hi @sj26, I'm not quite sure this fits my use case. I'm looking for a prompt (preferably only when running through the UI) to skip tests. If tests are skipped, there are still a few steps at the end that I want to run, like pushing Docker images, etc.

My understanding that a default `block` step is more to continue or fail a pipeline?

**Comment by renanberto** [comment]
Up ☝️

**Comment by renanberto** [comment]
I've a some question, with this pipeline:

```.yml
  - block: "Request release"
    prompt: "Fill out the details for release"
    fields:
      - text: "Version"
        key: "version"
        hint: "Include the version according to the standard: 2.x.x.x"
        required: true
      - select: "Type"
        key: "release-type"
        default: "stable"
        options:
          - label: "Stable"
            value: "stable"
          - label: "Beta"
            value: "beta"
          - label: "Debug"
            value: "debug"

  - wait

  - trigger: "stable"
    label: ":rocket: Release a stable version"
    if: $(buildkite-agent meta-data get release-type) == "stable"
```

Note this if depends the meta-data of `block` context

**Comment by sj26** [comment]
Sorry @evandam, I didn't notice the reply. 😞 

> I'm looking for a prompt (preferably only when running through the UI) to skip tests.

Something like:

```
steps:
  - input: "Run tests?"
    if: build.env("BUILDKITE_SOURCE") == "ui"
    fields
    - select: "Run tests?"
      key: "run-tests"
      options:
        - label: "Sure"
          value: "yes"
        - label: "No thanks"
          value: "no"

  - label: "Run tests"
    if: build.meta_data("run-tests") != "no"
    command: echo "test me!"
    plugins:
      - docker-compose#v3.1.0:
          run: app
```

The `build.meta_data(...)` here doesn't work, but this is a good use case for introducing it!

**Comment by sj26** [comment]
@renanberto that also sounds like a good use of a hypothetical `build.meta_data(...)` accessor in a conditional. 🤔

**Comment by sj26** [comment]
I've raised this with the team, I'll see if we can sneak it in. 🕺

**Comment by renanberto** [comment]
@sj26 Cool! tomorrow I'll spend a few hours to propose the change here: https://github.com/buildkite/conditional! I send it to you on the issue and here to see if I can help you with something!

Thanks for prioritizing!

**Comment by sj26** [comment]
Thanks for being keen, but that repo is the language, not how it is hooked up to builds. :-)

It's also been pointed out to me that my earlier example won't work. Conditionals are evaluated when a pipeline is uploaded.

So for a hypothetical example which might work after `build.meta_data(...)` were available:

```yaml
# .buildkite/pipeline.yml
steps:
  - input: "Run tests?"
    if: build.env("BUILDKITE_SOURCE") == "ui"
    fields
    - select: "Run tests?"
      key: "run-tests"
      options:
        - label: "Sure"
          value: "yes"
        - label: "No thanks"
          value: "no"
  - command: buildkite-agent pipeline upload .buildkite/pipeline-tests.yml
```
```yaml
# .buildkite/pipeline-tests.yml
steps:
  - label: "Run tests"
    if: build.meta_data("run-tests") != "no"
    command: echo "test me!"
    plugins:
      - docker-compose#v3.1.0:
          run: app
```

and if you're going to do that, then you could do it as a [dynamic pipeline](https://buildkite.com/docs/pipelines/defining-steps#dynamic-pipelines), i.e. a shell script with a few more smarts that does selective pipeline uploads.

**Comment by evandam** [comment]
@sj26 understood why this isn't possible with how things are done evaluating them at upload time, but would it be possible to see a larger "lazy evaluation" kind of mechanism for that would help support this?

Our pipelines end up looking a little crazy to the uninitiated Buildkite user, where this kind of syntax would make it much more obvious what's going on. The core use case for us at least is really the idea of an "optional step" determined by the use of an input/block step. Open to other ideas to implement this kind of thing too 🙏

**Comment by sj26** [comment]
@evandam yeah we've been having exactly that conversation, actually. It's a bit confusing which environment is available where and when. Conditionals probably add to this a little bit.

We'd love to support declarative conditionals, or something, but it's a big hairy problem which needs some very considered design. We're definitely stewing on it, though. 🙌

**Comment by sj26** [comment]
Hi folks! After a deep discussion we've decided not to support meta-data in conditionals just yet, sorry! We want to do it well, and have an answer for what happens when meta-data changes over the lifecycle of a build, and we haven't quite figured that out yet.

For now, you can do this with the buildkite-agent a bit of scripting — and it's not very different:

```yaml
# .buildkite/pipeline.yml
steps:
  - block: "Run tests?"
    if: build.env("BUILDKITE_SOURCE") == "ui"
    fields:
    - select: "Run tests?"
      key: "run-tests"
      options:
        - label: "Sure"
          value: "yes"
        - label: "No thanks"
          value: "no"
  - command: |
      if [[ "$(buildkite-agent meta-data get run-tests)" != "no" ]]; then
        buildkite-agent pipeline upload .buildkite/pipeline-tests.yml
      fi
```
```
# .buildkite/pipeline-tests.yml
steps:
  - label: "Run tests"
    command: echo "test me!"
```

This example is quite contrived. A simple block step with the conditional would work here. But if you had more complex options, it'd be a good beginning.

**Comment by sj26** [comment]
Hopefully the above will work, for now. We'll keep track of this feature request over in the forum — subscribe there for updates:
https://forum.buildkite.community/t/meta-data-in-conditional-clause/1190

**Comment by samuelneff** [comment]
I was able to use meta-data in conditionals without having to separate the pipeline into multiple files by loading them into environment variables, like this:

```
steps:
  - block: ":rocket: PROD Release!"
    prompt: You are about to create a new release. This cannot be undone.
    fields:
      - select: "Release type"
        key: "release_type"
        multiple: false
        options:
          - label: "Patch"
            value: "Patch"
          - label: "Minor"
            value: "Minor"
          - label: "Major"
            value: "Major"
          - label: "None (What are you doing here then?)"
            value: "None"
  - wait: ~

  - label: "Load release type into env variable"
    command: |
      export release_type=$(buildkite-agent meta-data get release_type)

  - wait: ~

  - label: "Triggering primarily pipeline to build and release"
    if: "build.env('release_type') != 'None'"
    command: |
      echo Building release of "$release_type"

  - label: "Cancelled release"
    if: "build.env('release_type') == 'None'"
    command: echo Cancelled release
```
