### ISSUE TITLE
wait step doesn't stop pipeline from running steps in parallel

### ISSUE THREAD

**Issue by b-b3rn4rd** [buildkite/agent#1168]
Hi guys,
The agent runs the first and last step simultaneously, despite the explicit `wait` step which in theory should block the last step "Terraform apply" until all previous steps have completed. 

I'm wondering if the issue is related to my conditional `block` step which supposed to run only in production. 

When I remove `if` statement it works as expected as well as if I remove the whole `block` step entirely - `wait` behaves as expected.

As you can see from the screenshot the pipeline recognizes that there is a `wait` step but doesn't respect it runs both steps at the same time (when **not** running against production).
![pipeline](https://i.ibb.co/xhzjrr6/Screen-Shot-2020-02-12-at-1-34-09-pm.png)
This is a simplified code from my pipeline file (I've removed hopefully unrelated code for brevity)
```
steps:
  - label: ':buildkite: Terraform generate execution plan'
    commands:
      - echo "hello"
  - block: ':rocket: Approval Step'
    if: build.env("ENVIRONMENT_NAME") == "production"

  - wait

  - label: ':buildkite: Terraform apply changes'
    commands:
      - echo "hello 2"
```

Alternatively, if this is an expecting behaviour could you please provide me with an example of how to introduce a manual block step when deploying to production env while always running steps in sequence (preferably keeping code in a single `yaml` file)

**Comment by jufemaiz** [comment]
Just confirming that the apply shouldn't happen without being in the correct env either?

```
steps:
- id: terraform-plan
  label: ':terraform: create plan'
  commands:
  - '.buildkite/plan.sh'
- block: ":terraform: apply changes"
  if: build.env("ENVIRONMENT_NAME") == "production"
- id: terraform-apply
  if: build.env("ENVIRONMENT_NAME") == "production"
  commands:
  - '.buildkite/apply.sh'
```

Should work for you to achieve what you're attempting (we have this working for us).

**Comment by b-b3rn4rd** [comment]
@jufemaiz thanks for the reply, in our case we would like to run `terraform apply` for any environments, however we want to have a manual approval `block` step if environment is production and just a normal `wait` for non production. Basically the workflow should look like this:

Production: `terraform plan -> block (manual approval) -> terraform apply`
Non Production: `terraform plan -> wait for plan to finish -> terraform apply`

**Comment by jufemaiz** [comment]
Just for giggles, try adding your if on the wait for the opposite?
```
steps:
- id: terraform-plan
  label: ':terraform: create plan'
  commands:
  - '.buildkite/plan.sh'
- wait:
  if: build.env("ENVIRONMENT_NAME") != "production"
- block: ":terraform: apply changes"
  if: build.env("ENVIRONMENT_NAME") == "production"
- id: terraform-apply
  if: build.env("ENVIRONMENT_NAME") == "production"
  commands:
  - '.buildkite/apply.sh'
```

?

**Comment by b-b3rn4rd** [comment]
@jufemaiz thanks for your help, I was playing around with the location of `wait` step and noticed that **if I put `wait` step above my conditional `block` it works as expected**, not sure if that's how it supposed to behave but at least I have a working solution :
```
env:
  ENVIRONMENT_NAME: uat
steps:
  - label: ':buildkite: Terraform generate execution plan'
    commands:
      - echo "plan"
 
 - wait

  - block: ':rocket: Approval Step'
    if: build.env("ENVIRONMENT_NAME") == "production"

  - label: ':buildkite: Terraform apply changes'
    commands:
      - echo "apply"
```

Thanks
