### ISSUE TITLE
[macos][docker][bk] allow macos agent to pass linux agent into docker

### ISSUE THREAD

**Issue by drnic** [buildkite/agent#1181]
[Sorry if I'm raising this against the wrong repo]

Currently when I use the docker plugin I configure it to `mount-buildkite-agent: true`:

```
steps:
  - label: ":ballot_box_with_ballot:"
    command: ./src/generate-and-store-number.sh
    plugins:
      - docker#v3.5.0:
          image: "starkandwayne/buildkite-base:latest"
          propagate-environment: true
          mount-buildkite-agent: true
```

The buildkite-agent mounts my host machine's `buildkite-agent` binary into the docker container.

Alas, if my host machine's architecture is different from the linux container (macos -> linux for example), then the binary will fail:

```
+ buildkite-agent meta-data get generated-number
./src/fetch-and-display-number.sh: line 14: /usr/bin/buildkite-agent: cannot execute binary file: Exec format error
```

This is probably not a production issue -- I wouldn't run my agent on my macOS for production pipelines -- but it is an issue for two use cases I'm affected by:

* local iteration of pipelines with `bk local run`
* initial user experience of buildkite.com before they commit to running agents on linux-based cloud servers

Could it be possible for `bk local run` and `buildkite-agent start` inject a linux buildkite-agent into docker, rather than arbitrarily passing in the host machine's binary?
