### ISSUE TITLE
allow_dependency_failure: true doesn't apply to timed out builds

### ISSUE THREAD

**Issue by davidlee1435** [buildkite/agent#1246]
Hey folks, we ran into an issue where a job timed out and it didn't trigger a dependency who's `allow_dependency_failures` flag was set to true.

![Screen Shot 2020-07-14 at 4 39 14 PM](https://user-images.githubusercontent.com/5074153/87486680-ab996080-c5f0-11ea-9b01-518b53e0c049.png)

Our YAML looks something like this:

```yml
  - label: Deploy
    agents:
      queue: ${QUEUE}
    timeout_in_minutes: 30
    concurrency: 1
    key: deploy-step
    ....
  - label: Send Slack Alerts
    command: ".buildkite/scripts/deploy_alerts_to_slack.rb"
    depends_on: deploy-step
    allow_dependency_failure: true
```

Is this a known issue? If not, are we doing something wrong?

**Comment by liamdawson** [comment]
It feels like a discrepancy, at minimum. Given the following pipeline:

```yaml
steps:
  - label: Time out
    key: time-out
    timeout_in_minutes: 1
    command: sleep 120

  - wait: ~
    key: continuing-wait
    continue_on_failure: true

  - label: Test A
    command: "true"

  - wait:

  - label: Test B
    depends_on: time-out
    allow_dependency_failure: true
    command: "true"

  - label: Test C
    depends_on: continuing-wait
    allow_dependency_failure: true
    command: "true"
```

- Test A passes
- Test B sits there with the "waiting" clock, like your example above
- Test C passes
