### ISSUE TITLE
Using $BUILDKITE_JOB_ID in a command gives me the previous step's job_id

### ISSUE THREAD

**Issue by jmchuster** [buildkite/agent#1247]
I have a pipeline where two steps are run in parallel, both with the commands
```
- commands:
    - docker run --name ${BUILDKITE_JOB_ID} ${DOCKER_IMAGE} /bin/sh ...
```

However, when I run this (and all three steps end up running on the same agent), it uses the previous step's job id, which of course causes docker to fail, since you can't run two images with the same name.

I would expect it to use the `BUILDKITE_JOB_ID` shown under the `Environment` tab, but it seems like it gets set after the pipeline script is parsed and the command is calculated.

**Comment by justinjdickow** [comment]
I have a similar issue. I'm setting environment variables in steps like

```
steps:
  - label: "First Step"
    command: "MYSQL_PORT=3308 scripts/script.sh"
  - label: "Second Step"
    command: "MYSQL_PORT=3309 scripts/script.sh"
```
So that if they're run in parallel on the same machine with different agents the MYSQL_PORT is isolated (different docker containers with different port mappings). But the result is that the MYSQL_PORT variable does not set deterministically.

**Comment by keithduncan** [comment]
> However, when I run this (and all three steps end up running on the same agent), it uses the previous step's job id, which of course causes docker to fail, since you can't run two images with the same name.

This looks to be because of variable interpolation when uploading new pipeline steps. If I upload a pipeline like this:

```yaml
---
steps:
- command: echo "${BUILDKITE_JOB_ID}"
- command: echo "\${BUILDKITE_JOB_ID}"
```

And then open the Timeline tab for the job which uploads the pipeline, you can see the difference:

![Screenshot 2021-07-28 at 16 06 02](https://user-images.githubusercontent.com/22101/127272114-d3753802-1f10-4441-bee4-a11f561815e9.png)

The latter job appears to be what you want. You can accomplish this by escaping the variable as shown or by invoking `buildkite-agent pipeline upload` with the `--no-interpolation` argument.

---

> But the result is that the MYSQL_PORT variable does not set deterministically.

@justinjdickow I’m afraid I’m not able to reproduce this in a test pipeline, if you’re still experiencing issues with this could you get in touch with [Buildkite Support](https://buildkite.com/support) and include a link to a Pipeline Build that demonstrates the problem and we’ll investigate 🙏
