### ISSUE TITLE
Pipeline parsing of "pipeline.yml" failed (Expected identifier to start with a letter, got ?)

### ISSUE THREAD

**Issue by alanbccoe** [buildkite/agent#1267]
Similar to #584 I'm getting the error in the title trying to compare `$?` in a pipeline command step. Neither of these work regardless of quoting:

```
if [[ "\$?" == "0" ]]; then ...
if [[ "$$?" == "0" ]]; then ...
```

**Comment by yob** [comment]
Hi @alanbccoe,

Are you open to emailing us a copy of the pipeline.yml and/or a link to a failing build? That will help us recreate the issue and understand what's going on. We're at hello@buildkite.com

**Comment by alanbccoe** [comment]
OK let me see if I can do that. I get the same issue trying to test a regex in a command block too:
```
if [[ ! "$i" =~ org/(unit1|unit2)/[^/]+/[^/]+$ ]]
if [[ ! "$i" =~ org/(unit1|unit2)/[^/]+/[^/]+\$ ]]
```

**Comment by alanbccoe** [comment]
This should reproduce the issue (but I don't have time to test it right now unfortunately):
```
steps:
  - label: Validation
    command: |
      [[ "org/unit1/some/thing/else/invalid" =~ org/(unit1|unit2)/[^/]+/[^/]+\$ ]] && echo 'OK'
```
