### ISSUE TITLE
`branches: !master` still runs on master branch

### ISSUE THREAD

**Issue by jmchuster** [buildkite/agent#1281]
we have steps set up like so
```
  - label: ':pipeline: build_bare_essentials'
    branches: master
    commands:
      - buildkite-agent pipeline upload .buildkite/steps/build_bare_essentials.yml
      - buildkite-agent meta-data set "build_essentials_commit" ${BUILDKITE_COMMIT}
  - label: ':git: Fetch master build-essential commit'
    branches: !master
    commands:
      - git fetch origin master
      - git merge-base $(git log -n 1 origin/master --pretty=format:"%H") $(git rev-parse HEAD) | buildkite-agent meta-data set "build_essentials_commit"
```

On the feature branches, as expected, the first step is run and the second ignored.  When I test it on the master banch, however, both steps are being run.  I triggered the master branch build manually, if that is relevant.

Link if you have access to investigate:
https://buildkite.com/farmwise/farmwise-main/builds/294#29fd13ba-0935-43c2-9c77-0ff3c0a02b93

**Comment by sj26** [comment]
Hi @jmchuster! Hmm, exclamation points have special meaning in YAML, so you might need to add some quotes to tell YAML it's a string:

```
  - label: ':pipeline: build_bare_essentials'
    branches: master
    commands:
      - buildkite-agent pipeline upload .buildkite/steps/build_bare_essentials.yml
      - buildkite-agent meta-data set "build_essentials_commit" ${BUILDKITE_COMMIT}
  - label: ':git: Fetch master build-essential commit'
    branches: "!master"
    commands:
      - git fetch origin master
      - git merge-base $(git log -n 1 origin/master --pretty=format:"%H") $(git rev-parse HEAD) | buildkite-agent meta-data set "build_essentials_commit"
```

This is pretty specific issue which might be better over email — feel free to contact us at support@buildkite.com next time. :-)
