### ISSUE TITLE
Reject unknown yaml tags

### ISSUE THREAD

**Issue by sj26** [buildkite/agent#1283]
We often get issues where folks have typing an exclamation point in some yaml by accident, and the agent parses and silently ignores the problem. Most recently, https://github.com/buildkite/agent/issues/1281.

Syntax like this, which is a "master" yaml tag, should probably throw a syntax error or something:

```yaml
step
- branches: !master
  commands: echo hello world
```
