### ISSUE TITLE
Docker agent for linux/arm/v7

### ISSUE THREAD

**Issue by lcardito** [buildkite/agent#1372]
Hey folks,

Possibly related to https://github.com/buildkite/agent/issues/475 ?

I wanted to try the docker agent out on my Raspberry Pi4, I got a complete docker setup with a small swarm cluster and was hoping to add the buildkite agent as well.

Unfortunately looks like the docker image is only built for `linux/amd64` so that generates a warning. More importantly however is that the container doesn't even start 😢 

```
$ docker run --rm buildkite/agent:3 --help
Unable to find image 'buildkite/agent:3' locally
3: Pulling from buildkite/agent
Digest: sha256:798cafc06f5af9c866d1b9d43256dd8758da5f4345ee82c6dbc71b8d3ec33142
Status: Downloaded newer image for buildkite/agent:3
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
```

I thin that the warning might prevent me to deploy the container in a docker swarm cluster, but I was expecting it to run in standalone.. 

Thoughts?

**Comment by sj26** [comment]
Hi @lcardito! I'm afraid we don't ship a docker image for that architecture. We'd like to, but don't have solid plans or a timeline.

Until then, we do ship an arm binary so you can run the agent via [manual installation](https://buildkite.com/docs/agent/v3/installation#manual-installation). Or I think the debian/ubuntu instructions will also work on raspian, we also build debian packages and maintain an apt repo for arm, arm64 and armhf:

https://buildkite.com/docs/agent/v3

**Comment by lcardito** [comment]
Greetings @sj26 ! Got it, thanks! The Ubuntu instructions worked like a charm so going with that setup for now. Thank you! 💥

**Comment by zaneclaes** [comment]
I cobbled this together into a Dockerfile (below) and built it on a `Raspberry Pi 4 Model B Rev 1.1`. You can pull the image from `inzania/buildkite-agent-arm`. It's based upon `armhf`, and tbh I wouldn't know the correct tagging architecture to use here so I'm not going to bother (this meets my needs). I got the BuildKite prompt to show (with a missing token error) via `sudo docker run --rm inzania/buildkite-agent-arm:latest`.

<img width="1651" alt="Screen Shot 2021-05-29 at 10 24 44 AM" src="https://user-images.githubusercontent.com/2084821/120077546-1ec08f80-c068-11eb-84e5-2082cfb8b180.png">

Next I'll set up a Kubernetes deployment file to add to my home fleet so that the RPi agent joins the cluster via a token mounted onto the container. 

I'm not claiming to maintain this or anything. Just hoping to provide steps for BuildKite to integrate this into their own CI.

**buildkite-agent-armhf.Dockerfile**
```
FROM debian:stable

RUN apt-get update -y && apt-get install -y wget

ENV FN="buildkite-agent-linux-armhf-3.30.0.tar.gz"
RUN wget "https://github.com/buildkite/agent/releases/download/v3.30.0/$FN"
RUN tar -xf $FN

RUN mkdir ~/.buildkite-agent ~/.buildkite-agent/bin ~/.buildkite-agent/builds
RUN cp buildkite-agent ~/.buildkite-agent/bin
RUN cp bootstrap.sh ~/.buildkite-agent/bootstrap.sh

ENTRYPOINT ["/buildkite-agent", "start"]
```

**Comment by zaneclaes** [comment]
_10 minutes later_...

The image worked as a drop-in on a k8s fleet with an arm node already in the cluster. 
<img width="746" alt="Screen Shot 2021-05-29 at 10 43 43 AM" src="https://user-images.githubusercontent.com/2084821/120078053-c76fee80-c06a-11eb-8f41-43b23edf5ce2.png">

Here's the base yaml for a k8s resource which targets the processor type:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkite-agent-arm
  labels:
    app: agent-arm
    release: buildkite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-arm
  template:
    metadata:
      labels:
        app: agent-arm
        release: buildkite
    spec:
      hostname: condo
      serviceAccount: buildkite-agent
      containers:
        - name: agent-arm
          image: "inzania/buildkite-agent-arm:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: buildkite-agent
                  key: agent-token
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "beta.kubernetes.io/arch"
                  operator: In
                  values: ["arm"]
```
