### ISSUE TITLE
Plugins checkout does not work on WSL2

### ISSUE THREAD

**Issue by gilbertsoft** [buildkite/agent#1449]
I'm trying to using the plugin `docker-login` and this works fine in the most environments but not with WSL2. There we get the following error:

```
Error: Failed to checkout plugin docker-login: mkdir /etc/buildkite-agent/plugins: permission denied
```

Here is the screenshot of the log:

![grafik](https://user-images.githubusercontent.com/25326036/121156619-2393f900-c849-11eb-85fa-0df038a6866d.png)

This is the workflow configuration:

```yaml
  - command: ".buildkite/test.sh"
    plugins:
      - docker-login#v2.0.1:
          username: druddockerpullaccount
          password-env: DOCKERHUB_PULL_PASSWORD
    agents:
      - "os=wsl2"
      - "architecture=amd64"
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
      BUILDKITE_BUILD_PATH: ~/tmp/buildkite_builds
      BUILDKIT_PROGRESS: plain
    parallelism: 1
```

The following combinations are working fine:

* linux / amd64
* linux / arm64
* macos / dockerformac / amd64
* macos / dockerformac / arm64
* windows / dockerforwindows / amd64

The related PR can be found here https://github.com/drud/ddev/pull/3041 and the failing build https://buildkite.com/drud/ddev-wsl2/builds/485#88ed67e9-fc83-4bd9-a579-758e24ebeb4a.
