### ISSUE TITLE
depends_on does not accept spaces, when depended on job finishes, nothing happens

### ISSUE THREAD

**Issue by Komorebi-E** [buildkite/agent#1450]
A pipeline is auto generated by comparing Packer JSON files for a repo to know if the AMIs need rebuilding.

If `depend_ons:` has a value with spaces for a labeled command, then it fails with this error. See "Not working" below.

> FATAL  Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/9da18506-3f5d-4d1c-af98-b433607a7176/pipelines: 422 `step` may only contain alphanumeric characters, slashes, dashes or underscores

If the spaces are replaced with '_' for the label and the `depends_on:` then the validation tasks runs in parallel but the task that is depending on them does nothing, it has no logs. See 50% working below and the screen grabs.

The objective is to have the as many validate then build AMIs running in parallel as our agents allow. Otherwise they have to run in series. A `-wait` was tried between the Validate and Build AMI, which then makes this very manual.

**UPDATE: If a key is used as per the documentation to identify each step for the `depends_on` then the pipeline behaves as expected.**
So the issues I see are:
-  The error is not specific about a key not being used.
- That it is possible to have a valid pipeline for syntax that uses a label ID for the depends_on but nothing is output for the failure of the task that depended on it.

**working**

```yaml
steps:
  - block: ":rocket: Validate and Build :packer: AMIs"
    branches: "!master"
    key: "human_says_go"

  - label: "Validate customer-base Packer File"
    key: "validate_customer-base"
    command:
      - "./validate.sh customer-base-image.json"

  - label: "Build customer-base AMI"
    depends_on:
      - "humans_says_go"
      - "validate_customer-base"
    command:
      - "./build.sh customer-base-image.json"
...
```

**Not working**

```yaml 
steps:
  - block: ":rocket: Validate and Build :packer: AMIs"
    branches: "!master"
  - label: "Validate customer-base Packer File"
    command:
      - "./validate.sh customer-base-image.json"

  - label: "Build customer-base AMI"
    depends_on: "Validate customer-base Packer File"
    command:
      - "./build.sh customer-base-image.json"
   
  - label: "Validate_customer-bastion_Packer_File"
    command:
      - "./validate.sh customer-bastion-image.json"

  - label: "Build customer-bastion AMI"
    depends_on: "Validate customer-bastion Packer File"
    command:
      - "./build.sh customer-bastion-image.json"
```

**50% working:**

Without spaces, this will do the validation tasks in parallel but the build task does nothing.

```yaml
steps:
  - block: ":rocket: Validate and Build :packer: AMIs"
    branches: "!master"
  - label: "Validate_customer-base_Packer_File"
    command:
      - "./validate.sh customer-base-image.json"

  - label: "Build customer-base AMI"
    depends_on: "Validate_customer-base_Packer_File"
    command:
      - "./build.sh customer-base-image.json"
  - label: "Validate_customer-bastion_Packer_File"
    command:
      - "./validate.sh customer-bastion-image.json"

  - label: "Build customer-bastion AMI"
    depends_on: "Validate_customer-bastion_Packer_File"
    command:
      - "./build.sh customer-bastion-image.json"
 ```

![image](https://user-images.githubusercontent.com/11135071/121217851-8655b680-c882-11eb-9ef2-dd3f72d27b2c.png)

![image](https://user-images.githubusercontent.com/11135071/121218058-b1400a80-c882-11eb-9609-93883ec7fb51.png)
