### ISSUE TITLE
Plugin config values as arrays not being set up as ENV vars

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#209]
If you have the following plugin config in a pipeline:

``` yml
myplugin:
  some-config-single: value
  some-config-array:
    - one
    - two
    - three
```

you end up with only a `BUILDKITE_PLUGIN_SOME_CONFIG_SINGLE=value` env var defined, no array. I'm not 100% sure what the syntax should be?
