### ISSUE TITLE
Make the uploading of artifacts consistant when using steps or cli ...

### ISSUE THREAD

**Issue by justinhennessy** [buildkite/agent#292]
Currently if you set `BUILDKITE_ARTIFACT_UPLOAD_DESTINATION ` you are able to upload an artifact using a step param as such:

```
-  name: "terraform plan"
   command: "bin/plan"
   artifact_paths: "*.plan"
   branches: "master"
   agents:
     queue: staging
```

But when you are using the command line you have to specify the bucket name:

`buildkite-agent artifact upload *.plan <bucket_URL>`

It would be good if the behaviour was consistant.
