### ISSUE TITLE
Inline hooks

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#296]
Here is a proposal to have inline hooks with a build job. So currently there a few places you can have hooks:

1. Global hooks
2. Per-pipeline hooks
3. Plugin hooks

How about we have inline hooks as well, like:

```
steps:
  - command: "my-script.sh"
    hooks:
      environment: "echo 'run at the every beginning'"
      post-checkout: "echo 'after the code is checked out'"
      post-artifact: "echo 'run after artifacts are uploaded"
```

The list of hooks we could support here:

- environment
- pre-checkout
- checkout
- post-checkoutt
- pre-command
- ~~command~~
- post-command
- pre-artifact
- post-artifact

What do you think?
