### ISSUE TITLE
Unable to turn off git submodule sync with env vars from documentation

### ISSUE THREAD

**Issue by KonstantinSimeonov** [buildkite/agent#3345]
Duplicate of https://github.com/buildkite/agent/issues/1053, but creating a new issue, since I cannot post there. I've tried disabling git submodules for a couple of reasons using the environment variable [BUILDKITE_GIT_SUBMODULES=false](https://buildkite.com/docs/pipelines/configure/environment-variables#BUILDKITE_GIT_SUBMODULES) in the `env` file which is sourced by the [Elastic CI AWS Stack](https://buildkite.com/docs/agent/v3/aws/elastic-ci-stack). I have verified that the variable is indeed exported and available during the clone step by using this debug pipeline config:

```yaml
steps:
  - label: ":pipeline:"
    command: env | grep SUBMODULE
    plugins:
      - "uber-workflow/run-without-clone"
```

<img width="811" alt="Image" src="https://github.com/user-attachments/assets/41ca3cd8-5104-46d6-b5aa-c0d160b16d53" />

Is it possible to disable the submodule operations during checkout with an env var, or I'll need to fork the AWS Stack and hack around this in the systemd definition or in the agent hooks?
