### ISSUE TITLE
ENV interpolation and invalid YAML

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#346]
Given this:

```yaml
  - trigger: "deploy"
    label: ":shipit:"
    branches: "master"
    async: true
    build:
      message: ${BUILDKITE_MESSAGE}
      commit: ${BUILDKITE_COMMIT}
      branch: ${BUILDKITE_BRANCH}
```

And a `BUILDKITE_MESSAGE` of

"Bumped frontend (:sasslang: emoji)"

becomes...

```yaml
  - trigger: "deploy"
    label: ":shipit:"
    branches: "master"
    async: true
    build:
      message: Bumped frontend (:sasslang: emoji)
      commit: ...
      branch: ...
```

you end up getting an error from Buildkite "There was an error parsing the config file. Maybe it's invalid YAML?"

I think after we do the interpolation we end up creating an invalid YAML file. Instead of doing an interpolation over the entire file (just treat the whole thing as text) I think we need to parse the YAML locally, recursively search over the structure, and interpolate each value individually.

**Comment by toolmantim** [comment]
Can we not just tell people to make sure they add quotes? And have nicer errors for when the `yml` parsing fails… (like outputting the YML, and even w/ line numbers and a good error message that says which line number)

```
  - trigger: "deploy"
    label: ":shipit:"
    branches: "master"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
```
