### ISSUE TITLE
Docker volume artifact error.

### ISSUE THREAD

**Issue by one19** [buildkite/agent#356]
If a volume is mounted that points to a non source-controlled folder location, subsequent tests will fail to clean up the leftover file, and render the pipeline for that branch stuck.

For example, using this docker-compose: 

```
version: '2'
services:
  ecsdefiner:
    image: someplace/some-image
    environment:
      TASK_DEF_OUTFILE: /opt/app/dist/taskdef.json
    volumes:
      - ./dist:/opt/app/dist
```

That `/dist` folder isn't part of source control. The expected artifact `taskdef.json` is able to be grabbed, but after that step, the build totally fails to clean it, and all subsequent pushes to any branches on that project will fail. The only way to escape the loop is to manually clean the artifact. 

Issue [#120](https://github.com/buildkite/agent/issues/120) talks about direct access to docker image contents, and would solve issues like these going forward, if it was implemented.
