### ISSUE TITLE
Artifact downloads in step config

### ISSUE THREAD

**Issue by tigris** [buildkite/agent#398]
It would be super cool if steps didn't have to manually download artifacts. That way, scripts could be run locally, and make assumptions that said artifact will exist on disk. Since if run locally, it should be safe to assume someone ran the steps in order.

Currently I am using a `pre-command` hook that looks like this:

``` bash
DOWNLOADS="${ARTIFACT_DOWNLOADS:-}"
DOWNLOAD_PATH="${ARTIFACT_DOWNLOADS_PATH:-.}"

mkdir -p "${DOWNLOAD_PATH}"

IFS=":"

for path in ${DOWNLOADS[@]}; do
  buildkite-agent artifact download "${path}" "${DOWNLOAD_PATH}"
done
```

I'm no bash expert, I'm sure there are better ways. But this allows you to specifcy an `ENV` var in your pipeline config, that will automagically download all artifacts you specify.

The downside to this is artifact upload "paths" are lost, and all downloads will be in 1 space, as a flat structure. Which is pretty annoying, but I've not bother to find a better solution yet.

It'd be super cool if we didn't need this hackery though. I'd really love a way to specify in step config that i want a particular artifact from a previous step to auto-exist in my folder structure. I wonder if named artifacts are the way to go? E.g.

``` yaml
steps:
  -
    name: artifact-generator
    command: ./generate-some-artifacts
    artifact_uploads:
      foo: 'target/*'
      bar: 'other/bar.txt'
  -
    name: artifact-consumer
    command: ./use-some-artifacts
    artifact_downloads:
      - foo
      - bar
```

Obviously an issue here would be file clobbering. I say let that be a lesson to the user.

**Comment by keithpitt** [comment]
@tigris thanks for talking us through what you're after!

> named artifacts

I've not actually thought of this before...and I actually think it's a really neat idea :) A while ago I was experimenting with some new features to the `pipeline.yml` file here: https://gist.github.com/keithpitt/bbe7851bc223741ff842be46d2cd14db (not that most of the features in here haven't even been created). But you'll see a new syntax for artifact uploading / downloading.

This pipeline is my attempt at taking our current deploy process and turning it into a BK pipeline - I think it has some potential! I really like your idea of named artifacts though, and I wonder how I can incorporate them!

**Comment by lox** [comment]
I would love this too!

**Comment by keithpitt** [comment]
👋 We're just doing some spring cleaning, and decided to close this issue for now. I'm planning a whole bunch of artifact upgrades this year (including a new upload/download syntax in the pipeline.yml file, and these changes will hopefully be included in that).

**Comment by rcoup** [comment]
For people coming across this, there's also https://github.com/buildkite-plugins/artifacts-buildkite-plugin:

```yaml
steps:
  - plugins:
      artifacts#v1.2.0:
        download: "log/**/*.log"
        upload: [ "log/**/*.log", "debug/*.error" ]
```
