### ISSUE TITLE
Support env interpolation in config keys

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#408]
For the buildkite-plugins/docker-compose-buildkite-plugin#16 I tried to make the plugin test use the plugin itself, but I noticed the `$` interpolation wasn't happening.

```yaml
steps:
  - command: /hello
    plugins:
      "${BUILDKITE_BUILD_CHECKOUT_PATH}#${BUILDKITE_COMMIT}":
        run: helloworld
        config:
          - docker-compose.yml
          - docker-compose.test.yml
```

It seems we don't support `$` interpolation of env keys, only values.
