### ISSUE TITLE
can't list multiple queues in UI

### ISSUE THREAD

**Issue by SydOps** [buildkite/agent#468]
@keithpitt 

As you guess, there could be a bug in the UI to display multiple queues in `Agent Targeting Rules` in pipeline setting.

```
queue=XXXX
queue=XXXX-prod
```

The section on the right has gone dark, that should be totally valid

Buildkite version: 2.5.1

### Update 1

I have to add a valid queue in UI at least, otherwise, the build will wait for `queue=default` forever, even though I set the queue in each step

```
- label: qa
  agents:
      queue: 'XXXX'
```
![screen shot 2017-05-11 at 11 18 18 am](https://cloud.githubusercontent.com/assets/8954908/25927773/9f784fac-363b-11e7-809a-40c08b8bb967.png)

### Update 2
In UI, I add one queue "queue=XXXX", but in `pipeline.yml`, I nominate different agent for different steps:

```
steps:
- label: qa
  agents:
      queue: 'XXXX'
      
- block

- label: prod
  agents:
      queue: 'XXXX-prod'
```

This works. Buildkite can use the nominated agent for different steps. 

But I still need your help to fix it in UI.
