### ISSUE TITLE
Downloading artifacts to '.' fails with confusing S3 error

### ISSUE THREAD

**Issue by toolmantim** [buildkite/agent#506]
If you try to download an artifact with the following syntax:

```
buildkite-agent artifact download some-dir/file.ext .
```

it’s able to find the artifact:

```
2017-07-19 12:21:26 INFO   Searching for artifacts: "some-dir/file.ext"
2017-07-19 12:21:27 INFO   Found 1 artifacts. Starting to download to: /Users/ci-machine/.buildkite-agent/builds/ios-build-server4.local-1/my-org/my-pipeline
```

but then fails with a permission error:

```
2017-07-19 12:21:54 ERROR  Failed to download artifact: Failed to create file /Users/ci-machine/.buildkite-agent/builds/ios-build-server4.local-1/my-org/my-pipeline/some-dir/file.ext (*os.PathError: open /Users/ci-machine/.buildkite-agent/builds/ios-build-server4.local-1/my-org/my-pipeline/some-dir/file.ext: permission denied)
2017-07-19 12:21:54 FATAL  There were errors with downloading some of the artifacts
```

The agent log will show it as an S3 download WARN log, which can make it seem like it's an S3 error. But it's actually a local path permission error.

It seems to work if you specify a sub-directory that exists, rather than `.`

"Download an artifact into the current working directory" should probably be a top use case for the `artifact download` command, and we should support `.` as a destination directory.

**Comment by lox** [comment]
👀

**Comment by lox** [comment]
Hrm, I'm not able to reproduce this. This was my test case:

```yaml
steps:
  - label: ":hammer: 1"
    command: 
      - "mkdir -p llamas"
      - "echo 'hello world' > llamas/hello.txt"
      - "cat llamas/hello.txt"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths:
      - "llamas/hello.txt"

  - wait
  - label: ":hammer: 2"
    command: 
      - "buildkite-agent artifact download llamas/hello.txt ."
      - "ls -alR"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
```
