### ISSUE TITLE
Agent 3.x cannot handle valid YAML pipeline definitions

### ISSUE THREAD

**Issue by stefanmb** [buildkite/agent#510]
Attempting to use `buildkite-agent pipeline upload` in beta 29 with a file like this:

```
base_step: &base_step
  type: script
  agent_query_rules:
    - queue=default

steps:
- <<: *base_step
  name: ':docker: building image'
  command: docker build .
  agents:
    queue: default
```

Results in:

> FATAL  Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/####/pipelines: 422 `<<` is not a valid property on the `command` step. Please check the documentation to get a full list of supported 

@toolmantim @keithpitt 
/cc: @DazWorrall @wvanbergen
