### ISSUE TITLE
Buildkite agent beta 33 breaks trigger steps

### ISSUE THREAD

**Issue by sander-m** [buildkite/agent#572]
We recently upgraded our agents to 3.0-beta-33, and this has introduced a critical bug.

**Triggered builds no longer build for the specified commit or branch**, but instead build for `master / HEAD` no matter what arguments are passed to the `trigger` step.

This is what our build steps look like:
```yaml
- trigger: "triggered-pipeline"
  build:
    message: ${BUILDKITE_MESSAGE}
    commit: ${BUILDKITE_COMMIT}
    branch: ${BUILDKITE_BRANCH}
```

With beta-33, this always run the build on `master / HEAD` for `triggered-pipeline`, rather than the current commit and branch.

## Why is this important?
Our pipelines are split up into separate pipelines with triggered builds. So this bug rendered our CI pipelines useless. As a result, this bug has caused our developers to merge failing builds to `master`.

**A rollback to beta 31 has fixed it.**
