### ISSUE TITLE
Environment variable substitution stopped working.

### ISSUE THREAD

**Issue by mgoodings** [buildkite/agent#647]
I cannot get environment variable substitution to work inside of the environment block at the top of the pipeline.yml after upgrading my Agent.

At the step level it seems to be working fine however it's necessary for me to use it at the environment block so all subsequent steps have the environment variables applied to them on execution.

This is using Agent v3.0-beta.38

![screen shot 2018-02-06 at 1 52 08 pm](https://user-images.githubusercontent.com/1767585/35839524-f8386012-0b44-11e8-9272-e715291d9dc9.png)

The same pipeline.yml running on Agent v3.0-beta.19

![screen shot 2018-02-06 at 1 54 12 pm](https://user-images.githubusercontent.com/1767585/35839582-485b2598-0b45-11e8-8046-9d87cbf687b4.png)

```
env:
  ACCOUNT: "${ACCOUNT?is not set. Please specify an account}"
  ENVIRONMENT: "${ENVIRONMENT?is not set. Please specify an environment}"
  BUILD_NUMBER: "${BUILDKITE_BUILD_NUMBER}"

steps:
  - name: ":docker: Build ${ENVIRONMENT}"
    command: ".buildkite/steps/build"
```

**Comment by lox** [comment]
Hey, sorry you're having problems @mgoodings. Let's figure out what is happening here. Do you happen to know what agent you were on before?

**Comment by lox** [comment]
Oh I just saw 🤦🏼‍♂️

**Comment by lox** [comment]
We changed our interpolation code in Beta 35. Let me investigate.

**Comment by lox** [comment]
Is your expectation that the `${ENVIRONMENT}` in the steps would be the environment from when the pipeline uploaded? If `$ACCOUNT` and `$ENVIRONMENT` weren't available in your pipeline upload step, would you expect the pipeline upload step to fail?

**Comment by lox** [comment]
Just to be sure, are you positive that a v3 agent handled the pipeline upload step?

**Comment by mgoodings** [comment]
I would expect the pipeline to fail, that's what it did before. I posted the versions of the agents being used.

**Comment by mgoodings** [comment]
Any progress on this?

Seem's pretty clear that:

```
env:
  ENVIRONMENT: "${ENVIRONMENT?is not set. Please specify an environment}"
```

Is not being interpolated at all and just being read as a raw string.

Then:

```
steps:
  - name: ":docker: Build ${ENVIRONMENT}"
```

Is being interpolated correctly and putting the value of $ENVIRONMENT which is now the raw string from the env block.

**Comment by lox** [comment]
I started looking into this and added a series of integration tests with exactly those cases and it behaved as expected, so I'm back to the drawing board at present.

When I create a pipeline with the yaml that you provided, this is what I get: 
![image](https://user-images.githubusercontent.com/15758/36135673-c7317aa2-10e0-11e8-8bcd-8fda48169d6f.png)

Could you drop us a support email with a pipeline that this is failing in so I can investigate? Could you also triple check that the pipeline upload step is running on an Agent v3? This would be exactly the behaviour that you would see if you used a v2 agent to do the pipeline upload.

**Comment by lox** [comment]
For reference, here are the interpolation test cases:

https://github.com/buildkite/interpolate/blob/master/interpolate_test.go#L241-L243

**Comment by mgoodings** [comment]
This is using an out of the box Elastic CI Stack v2.3.3 setup a week ago.

I just ran this on the agent today. Error shown and agent.

![screen shot 2018-02-13 at 5 23 39 pm](https://user-images.githubusercontent.com/1767585/36136091-d12ccba4-10e2-11e8-8c5f-1b3f0f864ed8.png)

![screen shot 2018-02-13 at 5 23 50 pm](https://user-images.githubusercontent.com/1767585/36136095-d5c93792-10e2-11e8-816f-c5a57e9c7af0.png)

Entire Pipeline YML:

```
env:
  ACCOUNT: "${ACCOUNT?is not set. Please specify an account}"
  PROJECT_SLUG: "${BUILDKITE_PIPELINE_SLUG}"
  BUILD_NUMBER: "${BUILDKITE_BUILD_NUMBER}"

steps:
  - block: ":rocket: Deploy to ${ACCOUNT}"

  - name: ":cloudformation: Deploy ${ACCOUNT}"
    command: .buildkite/steps/deploy
    agents:
      queue: bluesky
    plugins:
      irexchange/aws-assume-role#v0.1.0:
        role: "${DEPLOY_ROLE}"
      docker-compose#v1.8.2:
        run: deployer
```
