### ISSUE TITLE
Plugins with a `null` config shouldn't blow up

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#689]
We should probably just treat them as "plugins with 0 config". i.e this fails:

```yaml
steps:
  - plugins:
      detect-clowns#v2.0.0: ~
```
