### ISSUE TITLE
ERROR: mkdir /buildkite: read-only file system

### ISSUE THREAD

**Issue by torbjornvatn** [buildkite/agent#729]
Several incidents with this error message when using the Helm chart to set up agents:

https://github.com/kubernetes/charts/issues/3526

**Comment by toolmantim** [comment]
I’ve tried various permutations of volume configurations to try to solve this, but I couldn’t seem to get it to work with volume mounts.

I did get this DIND version working fine though:

```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: buildkite-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: buildkite-agent
    spec:
      containers:
        - name: buildkite-agent
          image: buildkite/agent
          imagePullPolicy: Always
          env:
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom: {secretKeyRef: {name: buildkite-agent, key: token}}
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          volumeMounts:
            - mountPath: /buildkite/builds
              name: buildkite-builds
        - name: docker-dind
          image: docker:dind
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            # Allows host volume mounts from buildkite-agent → docker-dind
            - mountPath: /buildkite/builds
              name: buildkite-builds
      volumes:
        - emptyDir: {}
          name: buildkite-builds
```

🤔

**Comment by lox** [comment]
I reckon the key distinction there @toolmantim is `buildkite-builds`. So rather than trying to host mount in `/buildkite` from the host OS (which is a bad idea with Container OS because it's read-only), the version you posted uses a named volume for builds, which is 💯.

**Comment by lox** [comment]
Figured out the issue. The path `/buildkite` doesn't exist on the host, it's in the buildkite-agent container. Trying to mount it causes docker to `mkdir /buildkite` on the host (default behaviour if sourceDir doesn't exist), and then you get the error about the host filesystem being read-only.

Solution is to use a writeable path on the host system for builds, and use exactly the same path in the buildkite-agent container.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: buildkite-agent
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: buildkite-agent
   spec:
     containers:
       - name: buildkite-agent
         image: buildkite/agent
         imagePullPolicy: Always
         securityContext:
           privileged: true
         env:
           - name: BUILDKITE_AGENT_TOKEN
             valueFrom: {secretKeyRef: {name: buildkite-agent, key: token}}
           - name: BUILDKITE_AGENT_DEBUG
             value: "true"
           - name: BUILDKITE_BUILD_PATH
             value: "/var/buildkite/builds"
         volumeMounts:
           - name: docker-binary
             mountPath: /usr/bin/docker
           - name: docker-socket
             mountPath: /var/run/docker.sock
           - name: buildkite-builds
             mountPath: /var/buildkite/builds
     volumes:
       - name: docker-binary
         hostPath: {path: /usr/bin/docker}
       - name: docker-socket
         hostPath: {path: /var/run/docker.sock}
       - name: buildkite-builds
         hostPath: {path: /var/buildkite/builds}
```
