### ISSUE TITLE
BUILDKITE_GIT_CLEAN_FLAGS is ignored

### ISSUE THREAD

**Issue by gtirloni** [buildkite/agent#756]
**Issue**:

BUILDKITE_GIT_CLEAN_FLAGS environment variable defined in pipeline.yml is set correctly but it's ignored by agent.

Setting the variable in the agent configuration achieves the desired behavior but it applies to all jobs and we only want this pipeline to have this behavior. Additionally, hiding the pipeline-specific configuration in the agent configuration means the code repository doesn't have all the configuration needed to run CI and it must be kept somewhere else.

We cannot have buildkite-agent deleting all files between jobs because they are dependent on each other. The "Build" step will start a virtual machine and that needs to keep existing for the other steps.

**Agent**:
buildkite-agent v3.1.1

**Pipeline**:
```yaml
env:
  BUILDKITE_GIT_CLEAN_FLAGS: "-fqd"
steps:
  - name: "Build"
    command: "DISPLAY=:0 vagrant up --provider virtualbox"
    timeout_in_minutes: 20
  - wait

  - name: "Code Linter"
    command: "vagrant ssh -c 'cd /home/vagrant/sync/; $(npm bin)/grunt lint'"

  - name: "Browser Tests"
    command: "npm run test:vagrantBrowser"

  - name: "Node Tests"
    command: "npm run test:vagrantNode"

  - wait: ~
    continue_on_failure: true

  - name: "Cleanup"
    command: "vagrant destroy -f"
```

**Example build**:
https://buildkite.com/fluid-project/fluid-infusion/builds/227#97cb4e7a-8544-4cbd-899d-274123dbeec0

**Logs**:

```
Preparing working directory | 1s
  | $ cd /home/buildkite-agent-1/builds/h-0005-tor1-inclusivedesign-ca-1/fluid-project/fluid-infusion
  | $ git remote set-url origin https://github.com/fluid-project/infusion.git
  | $ git clean -fxdq
....
# Cleaning again to catch any post-checkout changes
  | $ git clean -fxdq
```
