### ISSUE TITLE
Cancellation behavior on Windows and how to improve it?

### ISSUE THREAD

**Issue by amitsaha** [buildkite/agent#794]
On Windows, job cancellation is:

```
# process\process.go
if runtime.GOOS == "windows" {
    // Sending Interrupt on Windows is not implemented.
    // https://golang.org/src/os/exec.go?s=3842:3884#L110
   err = exec.Command("CMD", "/C", "TASKKILL", "/F", "/PID", strconv.Itoa(p.Pid)).Run()
```

This essentially (due to no fault of buildkite agent) means that the spawned process doesn't get any opportunity to perform any cleanup tasks. 

What do we do then if we want to run cleanup tasks when a job is cancelled?

**Allow custom cancel command**

Instead of using `signals` as the only supported mechanisms for indicating to the spawned process, we can allow a custom command to be executed. An example of a custom command may be invoking a HTTP API endpoint which will be exposed by the spawned process which will trigger the shutdown process as part of which it will perform cleanup tasks.

__How do we implement it?__

For example (to minimize changes across the board), the agent can look for a environment variable
`CANCEL_COMMAND`:

```
steps:

    - label:  ':hammer: Build and Run All Tests'
      command: 'powershell.exe -File .buildkite/scripts/RunTests.ps1'
      env:
          CANCEL_COMMAND: 'Invoke-WebRequest http://127.0.0.1:8000/cancel'
```

And then:

```
# process\process.go
func (p *Process) Kill() error {
       if os.Getenv("CANCEL_COMMAND") {
           # Execute the custom command
       } else {
          # Current signalling behavior
           # ..
	
    }
```

Of course what I propose here is going to be usable on non-Windows platforms as well. However, this would be useful most on Windows platforms. 

What do you folks think of this?
