### ISSUE TITLE
Feature request: Enumerate meta-data keys

### ISSUE THREAD

**Issue by moensch** [buildkite/agent#822]
I'd love to be able to enumerate meta-data keys. I am building pipelines for terraform, and I want to make it easy for my devs to set meta-data keys in an early step which later can be consumed by the terraform steps.

For example, an early step would have this in a build step:

```yml
steps:
  - label: build docker
    command:
     - docker build -t someimage:${BUILDKITE_COMMIT} .
     - docker push someimage:${BUILDKITE_COMMIT}
     - buildkite-agent meta-data set terraform/variables/docker_image someimage:${BUILDKITE_COMMIT}
```

Then, my terraform stuffs (for which I have a plugin), could have a pre-command hook to do something like this:

```bash
for var in $(buildkite-agent meta-data list 'terraform/variables/*'
do
  # TF_VAR_the_last_bit_after_the_final_slash
  tf_var_name="TF_VAR_$(echo $var | sed -e 's#.*/##')"
  printf -v $var_name $(buildkite-agent meta-data get $var)
  export $tf_var_name
done
```

I currently have a work-around in place where I provide a bash function for folks to set those meta-data keys and every time it is called, I keep track of all the variables as a comma separate list in a separate meta-data key.
