### ISSUE TITLE
pipeline.yml artifact_paths

### ISSUE THREAD

**Issue by ksykulev** [buildkite/agent#823]
`artifacts_paths` key definition in `pipeline.yml` only accepts a relative path. 
So for example (assuming my build step is running in the `app` directory):

This does not work:
```
# pipeline.yml
steps:
...
  - name: "some name"
    command: "command.sh"
    artifact_paths:
      - "/app/tmp/rspec-*.xml"
      - "/app/tmp/resultset-*.json"
```

However, this works:
```
# pipeline.yml
steps:
...
  - name: "some name"
    command: "command.sh"
    artifact_paths:
      - "tmp/rspec-*.xml"
      - "tmp/resultset-*.json"
```

Would love it if the documentation mentioned that specifically somewhere:
https://buildkite.com/docs/pipelines/defining-steps
https://buildkite.com/docs/pipelines/artifacts
https://buildkite.com/docs/agent/v3/cli-artifact

**Comment by lox** [comment]
Apologies for the slow response @ksykulev, that's surprising, absolute paths should work! Were you perhaps running inside a container? The artifact_paths would be relative to the host system vs the container in that case.

**Comment by ksykulev** [comment]
I was running inside a container. But let me expand a bit on my use case..

I have my `rspec` command outputting Junit formatted xml files and also code coverage json files:

`pipeline.yml` (original)
```
steps:
....
  - name: ":rspec:"
    command: ".buildkite/steps/rspec.sh"
    artifact_paths: "tmp/rspec-*.xml"
    plugins:
      docker-compose:
        run: app
    parallelism: 5
    timeout_in_minutes: 20
```

in specific..
`.buildkite/steps/rspec.sh` (original)
```
#!/bin/bash
...
bundle exec rake "knapsack_pro:rspec[--format progress --format RspecJunitFormatter --out /app/tmp/rspec-$BUILDKITE_JOB_ID.xml]"
```

The `app` directory comes from our `docker-compose.yml` file
`docker-compose.yml`
```
services:
...
  app:
    build: .
    volumes:
      - .:/app
```
And we check out our project to `/the-project-name` in our `Dockerfile`
`Dockerfile`
```
...
RUN mkdir /the-project-name
WORKDIR /the-project-name
ADD . /the-project-name
...
```

So as you can see it spits out the files to `/app/tmp/rspec-[N].xml` which is great because it's easily configurable from the command line. But the code coverage tool I'm using is a bit less configurable and spits out files to `/the-project-name/coverage/.resultset.json` - 5 files in the respective parallelized container directories. 

I want these json files to be accessible for a later build step, so I figured I would put them in the same directory as the xml files.

So my file was changed to:
`.buildkite/steps/rspec.sh`
```
#!/bin/bash
...
bundle exec rake "knapsack_pro:rspec[--format progress --format RspecJunitFormatter --out /app/tmp/rspec-$BUILDKITE_JOB_ID.xml]"

mv -v /the-project-name/coverage/.resultset.json /app/tmp/resultset-${BUILDKITE_PARALLEL_JOB}.json
```

And thus my pipeline.yml file:
`pipeline.yml`
```
  - name: ":rspec:"
    command: ".buildkite/steps/rspec.sh"
    artifact_paths:
      - "tmp/rspec-*.xml"
      - "tmp/resultset-*.json"
    plugins:
      docker-compose:
        run: app
    parallelism: 5
    timeout_in_minutes: 20
```

But when I tried to change the `artifact_paths:` to:
`pipeline.yml`
```
    artifact_paths:
      - "/app/tmp/rspec-*.xml"
      - "/app/tmp/resultset-*.json"
```
(which made more sense to me...) at the time, it did not seem to find the files. However, I haven't tried to fiddle around with these settings recently...

Might this not be the recommended way of handling something like this?
Let me know if you need anymore clarification on our build procces.
