### ISSUE TITLE
Environmental Variables Containing Secrets Visible in UI Environment tab

### ISSUE THREAD

**Issue by bobhenkel** [buildkite/agent#835]
In my pipeline.yaml I'm doing something like this:

```
steps:
  - label: ":docker: Build/Test/Tag"
    command:
      - docker build  -t $${PIPELINE_DOCKER_REGISTRY_URL}:$${PIPELINE_IMAGE_TAG} .
      - docker run --rm $${PIPELINE_DOCKER_REGISTRY_URL}:$${PIPELINE_IMAGE_TAG} $$PIPELINE_TEST_DOCKER_IMAGE_COMMAND
      - docker login  -u $$DOCKER_USER -p $$DOCKER_PASS
    env:
        PIPELINE_TEST_DOCKER_IMAGE_COMMAND: ${PIPELINE_TEST_DOCKER_IMAGE_COMMAND}
        PIPELINE_DOCKER_REGISTRY_URL: ${PIPELINE_DOCKER_REGISTRY_URL}
        PIPELINE_IMAGE_TAG: ${PIPELINE_IMAGE_TAG}
        DOCKER_USER: $DOCKER_USER
        DOCKER_PASS: $DOCKER_PASS
    agents:
      queue: 'default'
```

The problem is $DOCKER_USER and $DOCKER_PASS show up in the Environment tab in the Buildkite UI. Is there a way to mark these as secrets so they're * our in the UI?  Not all users who can see the build should be seeing the value of these types of secrets.

Thanks!
