### ISSUE TITLE
Can the port be made optional in BUILDKITE_METRICS_DATADOG_HOST? 

### ISSUE THREAD

**Issue by yob** [buildkite/agent#868]
We've just upgraded a few agents to 3.6.0 and tried out the datadog integration.

One thing that caught us out is the `BUILDKITE_METRICS_DATADOG_HOST` env var requires a port (ie `x.x.x.x:8125`, not `x.x.x.x`). Leaving it off is a fatal error. Port `8125` is the default port for dogstatsd - could the port be made optional?

It's not a huge issue, but for those on GKE (like us) it requires some gymnastics to work around and might be confusing for anyone new to kube. For reference, we were able to insert the port using interpolation in env vars:

```yaml
            env
            - name: BUILDKITE_METRICS_DATADOG
              value: "1"
            - name: DATADOG_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: BUILDKITE_METRICS_DATADOG_HOST
              value: "$(DATADOG_HOST):8125"
```
