### ISSUE TITLE
Propagate caller environment when using dynamic pipelines

### ISSUE THREAD

**Issue by mr-beerkiss** [buildkite/agent#953]
It would seem that neither global pipeline environment settings, nor local step environments settings are propagated when calling dynamic pipelines.  

Consider the following dynamic pipelines:

```
steps:
  - label: Test
    command:
      - 'echo "Triggered dynamic pipeline...."'
      - 'echo "GLOBAL: $${MY_GLOBAL_ENV_VAR}"'
      - 'echo "LOCAL: $${MY_LOCAL_ENV_VAR}"'
    agents:
      queue: myqueue
    plugins:
      - docker#v3.0.1:
          image: "busybox"
          propagate-environment: true
```

And the pipeline that calls it

```
env:
  MY_GLOBAL_ENV_VAR: "hello global"
steps:
  - command: aws s3 cp s3://<bucket>/pipeline.yml - | buildkite-agent pipeline upload
    agents:
      queue: artefacts:npm
    env:
      MY_LOCAL_ENV_VAR: "hello local"
```

I would expect the output from the `Test` step to print the following

```
Triggered dynamic pipeline....
GLOBAL: hello global
LOCAL: hello local
```

But instead, the output is
```
Triggered dynamic pipeline....
GLOBAL:
LOCAL:
```

I realise this is a trivial example, and by only using a single `$` sign in the `Test` step then pipeline interpolation would solve this particular problem.  However, my specific use case requires the host environment to be populated since in reality most of my build steps are defined in shell scripts where variable interpolation is of no use to me.

A pipeline variation without the Docker plugin yields results.

**Comment by runk** [comment]
@lox can you look into this please?

**Comment by lox** [comment]
Apologies @runk, haven't had a chance yet, have you emailed support@buildkite.com?

**Comment by lox** [comment]
I suspect this is going to be related some subtleties around how `propagate-environment` works in the docker plugin. I'll see if I can replicate.

**Comment by mr-beerkiss** [comment]
@lox I see similar behaviour without the Docker plugin (I mentioned that in my notes).  Sorry if that caused confusion, the way I've expressed the example with the plugin is much closer to our use case.

**Comment by sagebind** [comment]
Based on what the UI shows me in the `Environment` tab, it looks like "global" environment variables are being scoped to particular pipeline files being uploaded. So if you have a pipeline like this (`.buildkite/pipeline.yml`):

```yaml
env:
  FOO: bar

steps:
  - label: "Another pipeline"
    command: "buildkite-agent pipeline upload .buildkite/pipeline-too.yml"
```

with `.buildkite/pipeline-too.yml` containing:

```yaml
env:
  BAZ: bar

steps:
  - label: "Print"
    command: "echo FOO = $${FOO}, BAZ = $${BAZ}"
```

The variable `FOO` is made available only to steps defined in `.buildkite/pipeline.yml`, and the variable `BAZ` is made available only to steps defined in `.buildkite/pipeline-too.yml`. I suspect this pattern continues if you daisy-chain more pipeline uploads.

While it could be argued that this behavior makes sense, it isn't the behavior I expected, and is arguably less useful.

**Comment by moensch** [comment]
I am seeing this too (and now also have a use case where this gets annoying) and it's not just a `propagate-environment` thingy. Any "global" env vars (set at the top level `env` block) go lost when you upload a new dynamic pipeline. Only original pipeline steps have them.

**Comment by lox** [comment]
Ah right, I believe that is by design, the top-level env are scoped to that pipeline upload. @keithpitt do you know more about this?

**Comment by mr-beerkiss** [comment]
@lox if it's by design does that mean I should be seeking an alternative to environment variables to pass values into dynamic pipeline scripts?

**Comment by askoufis** [comment]
Has there been any follow on this? We've come across another use case where it would be really handy to be able to propagate certain environment variables into dynamic pipelines.

**Comment by lox** [comment]
Currently it's behaving as designed. Environment defined in a top-level `env` block is scoped to the pipeline being uploaded. 

The env will however be available to the `pipeline upload` though for interpolation.

The trick would be to set the ENV explicitly like this:

#### pipeline.yml

```yaml
env:
  FOO: bar

steps:
  - command: "buildkite-agent pipeline upload another.yml"
  - wait
  - command: "echo FOO = $${FOO?}, BAZ = $${BAZ:-not set}"
```

#### another.yml

```yaml
env:
  FOO: ${FOO}
  BAZ: bar

steps:
  - command: "echo FOO = $${FOO?}, BAZ = $${BAZ?}"
```

Hope that helps! Going to close this for now, let me know if I can explain in more detail!
