### ISSUE TITLE
EKS tags not filter correctly, BUILDKITE_AGENT_TAGS allows non-tagged pipeline to run

### ISSUE THREAD

**Issue by kenneyhe-snapdocs** [buildkite/agent#959]
### Actual:
  non-tagged pipeline (pipeline without any agent is using EKS agents). 

### Expect:
  I expect that EKS pipeline will be going to eks agent only when using below pipeline.yml.  Vice versa, pipeline with no agent should not used EKS agent which is tagged.
  
  File:
```
    steps:
  - label: ":docker: Building Docker Image"
    command: script/build_image.sh
    env:
      - AWS_REGION=us-west-2
      - EB_APP_NAME:"maintenance"
      - ECR_ID:"764270331768"
      - S3_EB_APP_BUCKET_NAME:"elasticbeanstalk.snapdocs.com"
      - EnvironmentName: buildkite
    agents:
      eks:'*'
```

  Agent (3.2.0)  runs ie:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: buildkite-agent
  name: buildkite-agent
  namespace: ci-ct-cd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: buildkite-agent
    spec:
      containers:
      - env:
        # We inject the AWS authentication as standard AWS environment variables here.
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              key: region
              name: aws
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access-key-id
              name: aws
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secret-access-key
              name: aws
        # Here's that buildkite build token.
        - name: BUILDKITE_AGENT_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: buildkite
        # Here's our authentication to the kubernetes cluster. We will reference these environment
        # variables later when we are making kubectl commands.
        - name: KUBE_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: clusters
        - name: KUBE_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: clusters
        - name: BUILDKITE_AGENT_WHITELIST_PIPELINES
          value: "maintenance,snapdocs"
        - name: BUILDKITE_AGENT_ALLOW_FORKS
          value: "true"
        - name: BUILDKITE_AGENT_PRIORITY
          value: "1999"   
        - name: BUILDKITE_AGENT_TAGS
          value: "eks=true,queue=default"
        - name: BUILDKITE_METRICS_DATADOG_HOST
          value: "datadog-agent.default.svc:8125"
        # You can replace this image with whatever you'd like if your needs require other devops
        # or testing environment tooling.
        #image: buildkite/aws-agent-with-whitelist:latest
        #image: mikehock/buildkite-agent-aws-kube:latest
        image: buildkite/agent:latest

        # Here, we define a postStart lifecycle hook to log us into AWS ECR. This command could be
        # ran during the build pipeline, but you'll need to make sure its ran on the _same agent_
        # that is actually doing the push, which isn't always a guarantee with BuildKite unless
        # you include it in the same pipeline step as the push. Instead, we just run it here when
        # the container starts.

        name: buildkite-agent
        args: [ "start", "--debug", "--debug-http"]
        # In order to do docker builds, we need to grant a privileged security context to this 
        # container.
        securityContext:
          privileged: true
        volumeMounts:
        # Here, we mount our ssh key into the container
        - mountPath: /root/.ssh/id_rsa
          name: ssh-keys
          subPath: id_rsa
        - mountPath: /root/.ssh/id_rsa.pub
          name: ssh-keys
          subPath: id_rsa.pub
        # We also mount the docker binary and the docker socket, which the container is allowed to
        # access because it is running in privileged mode.
        - mountPath: /usr/bin/docker
          name: docker-binary
        - mountPath: /var/run/docker.sock
          name: docker-socket
      volumes:
      - hostPath:
          path: /usr/bin/docker
          type: ""
        name: docker-binary
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: docker-socket
      - secret:
          defaultMode: 256
          secretName: ssh
        name: ssh-keys
```
