### ISSUE TITLE
Issue piping into annotate

### ISSUE THREAD

**Issue by shavo007** [buildkite/agent#972]
Hi,

I am trying to pipe some stdout into buildkite annotate.

Step looks like

```
  - label: "Serverless :serverless: Deploy Production  :shipit:"
    <<: *prod-agent
    plugins:
      <<: *plugins
    command:
      - echo "--- Running yarn install :yarn:"
      - yarn
      - echo "--- Running serverless deploy to prod  :serverless:"
      - npx sls deploy --stage prod -v
      - echo "--- Serverless production metrics :serverless:"
      - npx sls metrics --stage prod | terminal-to-html | buildkite-agent annotate  --style info
    branches: master  
```

Steps are:
yarn install
serverless deploy
then pipe serverless metrics into `terminal-to-html` to build agent annotate

I am using the docker plugin, which is my own to run the commands

Dockerfile looks like 

```
FROM mhart/alpine-node:11

RUN apk --no-cache update \
&& apk add --no-cache bash curl wget \
&& curl -L -o terminal-to-html.gz https://github.com/buildkite/terminal-to-html/releases/download/v3.1.0/terminal-to-html-3.1.0-linux-amd64.gz \
&& gzip -d terminal-to-html.gz \
&& mv terminal-to-html /usr/bin/terminal-to-html \
&& chmod +x /usr/bin/terminal-to-html \
&& mkdir -p /app

RUN rm /var/cache/apk/*

WORKDIR /app

COPY package.json yarn.lock .npmrc /app/

RUN yarn
```

The error i receive is 

```

Serverless production metrics | 4s
-- | --
  | Using original buildkite agent from /tmp/tmp.HiBBHi/buildkite-agent
  | grep: unrecognized option: text
  | BusyBox v1.28.4 (2018-12-31 18:05:13 UTC) multi-call binary.
  |  
  | Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...
  |  
  | Search for PATTERN in FILEs (or stdin)

```

Is my docker image missing a package. 

Or how do i ouput metrics into the annotation?

Thanks,
Shane.
